name: Deploy

on:
  workflow_dispatch:
    inputs:
      enviroment:
        description: "choose a deployment target."
        required: true
        default: "engineer"
        type: choice
        options:
          - engineer
          - test
          - prod
env:
  IMAGE_TAG: ${{ github.sha }}.${{ github.event.inputs.enviroment || 'production' }}
  REPO_NAME: ${{ github.event.repository.name }}
  DEPLOY_TARGET: ${{ github.event.inputs.enviroment || 'production' }}
jobs:
  PullSource:
    runs-on: ubuntu-latest
    name: "PullSource"
    steps:
      - name: Pull source
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.ACCESS_TOKEN }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/deploy/password-app
            git checkout .
            git pull
            pnpm i
            cd ~/deploy/password-app/apps/server
            pnpm start
